### ISSUE TITLE
Metadata editor does not display saved data

### ISSUE THREAD

**Issue by jimdowling** [hopshadoop/hopsworks#176]
When you open the metadata editor that contains metadata for a file, it shows empty fields. However, the metadata is still stored in the database - it's a display issue.

**Comment by jimdowling** [comment]
If i edit a text field, it will add two rows to the database, and two entries.

**Comment by evsav** [comment]
It seems I couldn't stay out of this :)

Metadata displaying/editing takes place in the right hand side bar when you click on a file/folder. You can see all the attached metadata per table & per field where you can do in-place editing.

Displaying content in the metadata editor wouldn't be very helpful when you have several instances stored per field. E.g. 5 meta entries for a single text field wouldn't fit in the field. To enter new values you would have to reset the slider.

What is wrong though, is that you are allowed to edit values even for multi/single select fields which shouldn't happen. They are treated like text values (never thought about this until now)

**Comment by evsav** [comment]
I also have to mention that meta_raw_data is no longer holding the actual metadata values. Since the introduction of the multi-select value list metadata are stored in meta_data. I had to break down multi-select metadata into single values. 

Thus meta_raw_data represents a grouping of fields under a tuple, and meta_data represents a grouping of values under a field.

**Comment by jimdowling** [comment]
Ok, thanks. We will have to understand this better before we have some fix. I think the behaviour as it currently is, is a bit confusing for "data entry" people. Thanks for the feedback. Demoing this week in Berlin at FlinkForward :)

**Comment by evsav** [comment]
That's great. Hope everything goes well
