### ISSUE TITLE
Profile credential update fails for valid username passwords

### ISSUE THREAD

**Issue by gholamiali** [hopshadoop/hopsworks#193]
When users wants to update their credentials in the profile it fails despite with correct username/passwords

**Comment by kerkinos** [comment]
Ok, so one thing was in profile.html


          <input name="user_password_confirm" ng-model="profileCtrl.loginCredes.confirmedPassword"
                 match="regCtrl.newUser.chosenPassword"
                 class="form-control" type="password">


It should be match="profileCtrl.loginCredes.newPassword"
Changing that will solve the "The two passwords you entered do not match" issue.

A bit before that there is 


      <input name="user_old_password" ng-model="profileCtrl.loginCredes.oldPassword"
             match="profileCtrl.user.chosenPassword"
             class="form-control" type="password" required>


Trying to match to the current password. But profileCtrl.user.chosenPassword is not a thing in profile.js.
User only has 
```
self.user = {
              firstName: '',
              lastName: '',
              email: '',
              telephoneNum: '',
              registeredon: ''
            };
```

Finally in profile.js the changeLoginCredentials method looks like this.
```
self.changeLoginCredentials = function () {
              self.credentialWorking = true;
              if ($scope.credentialsForm.$valid) {
                UserService.changeLoginCredentials(self.loginCredes).then(
                        function (success) {
                          self.credentialWorking = false;
                          growl.success("Your password is now updated.", {title: 'Success', ttl: 5000, referenceId: 1});
                        }, function (error) {
                          self.credentialWorking = false;
                          self.errorMsg = error.data.errorMsg;
                          growl.error("Could not update your password.", {title: 'Error', ttl: 5000, referenceId: 1});
        });
    }
};
```
So even if it worked I don't think anything would change. 

Now I'm trying to figure out how the password is retrieved and updated abd I should be able to fix it

**Comment by kerkinos** [comment]
btw I'm trying this in develop. Should I change to newfrontend_security?

**Comment by gholamiali** [comment]
Develop is fine. I can pull your changes.

**Comment by jimdowling** [comment]
Yes, develop is fine.
