### ISSUE TITLE
Deleting project and datasets doesn't remove it from the UI

### ISSUE THREAD

**Issue by jimdowling** [hopshadoop/hopsworks#207]
You can't click on the project, but it is still there.

**Comment by jimdowling** [comment]
I suspect it is deleting the project from HDFS, but there is definitely still the row for the project left in the **project** table.

**Comment by jimdowling** [comment]
Actually, this could be the problem: 
the foreign key in projects is disabled.
#  FOREIGN KEY (`inode_pid`,`inode_name`) REFERENCES `hops`.`hdfs_inodes`(`parent_id`,`name`) ON DELETE CASCADE ON UPDATE NO ACTION

I still don't know what the fix is.

**Comment by kerkinos** [comment]
I just tried replicating it and it works for me. Projects and datasets are removed from the UI, hdfs and the database. Not sure what the difference in our configurations might be.

**Comment by jimdowling** [comment]
Fixed by fixing foreign keys.
