### ISSUE TITLE
Yubikey table JDBC updates are not commited to NDB

### ISSUE THREAD

**Issue by gholamiali** [hopshadoop/hopsworks#231]
This line returns 1 which means one row is affected in the Yubikey table but no changes are made in the table.

https://github.com/biobankcloud/CauthRealm/blob/master/src/main/java/se/kth/bbc/crealm/CustomAuthRealm.java#L502

**Comment by jimdowling** [comment]
I rebuilt Cauth and redeployed it. Did this fix the problem?
