### ISSUE TITLE
Problem deploying hopsworks on baremetal using karamel

### ISSUE THREAD

**Issue by sfarestam** [hopshadoop/hopsworks#246]
I'm using karamel to deploy hopsworks on a single baremetal node and am seeing an issue at the spark::install phase. Anyone have an idea on what the issue is? See below for gists containing the config, the karamel status screen and the error log.

Thanks,
Stefan

karamel configuration based on karamel-0.2/examples/testing/hopsworks-single-node.yml:
   https://gist.github.com/sfarestam/b743abf2b692b4d6babd

karamel status screen:
   https://gist.github.com/sfarestam/e2ed78fe8b98b231ddd6

spark Error
   https://gist.github.com/sfarestam/57aeffcefc1fa4a54155

**Comment by jimdowling** [comment]
Closing due to massive rewrites.
