### ISSUE TITLE
yarn_projects_quota not cascaded when a project is deleted

### ISSUE THREAD

**Issue by ErmiasG** [hopshadoop/hopsworks#256]
This will prevent a project with the same name as a deleted project from being created.
 com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException: Duplicate entry 'prjectOne' for key 'PRIMARY'
Error Code: 1062
Call: INSERT INTO hops.yarn_projects_quota (PROJECTNAME, quota_remaining, TOTAL) VALUES (?, ?, ?)
	bind => [prjectOne, 100, 0]
Query: InsertObjectQuery(se.kth.bbc.project.YarnProjectsQuota[ projectname=prjectOne ])

**Comment by kerkinos** [comment]
Should the project be deleted from the table then? What if there is still credit left? Should there be an id to make it unique or have a yarn_archived_projects_quota table and move the rows there?
