### ISSUE TITLE
Dataset Browser Improvements

### ISSUE THREAD

**Issue by jimdowling** [hopshadoop/hopsworks#262]
We should provide more functionality in the DataSet Browser:
- mv, rename files/folders
- delete files/directories
- change permissions and owner of files by the project owner (we may need to execute these as superuser)
- Change pagination size for files (dropdown list of sizes: 25, 50, 100, 250, 500, 1000)
- Trash
- Others?

See some tips from Hue:
https://www.youtube.com/watch?v=2sWjlVxRHFk

**Comment by tkakantousis** [comment]
Move, rename, delete has been implemented.
