### ISSUE TITLE
ProjectPaymentsHistory More than one result was returned from Query.getSingleResult()

### ISSUE THREAD

**Issue by ErmiasG** [hopshadoop/hopsworks#264]
ProjectPaymentsHistory findByProjectName 
More than one result was returned from Query.getSingleResult()
b/c project name is not unique and payment history of a deleted project is still in the db it can return multiple results.

**Comment by kerkinos** [comment]
It makes sense that more than one result would be returned since there could be multiple transaction made. I have it set to return the last transaction so that shouldn't return duplicates. How can I reproduce it?
