### ISSUE TITLE
Account validation

### ISSUE THREAD

**Issue by gholamiali** [hopshadoop/hopsworks#332]
This new function creates the user registration process. A username is defined to be a 8 character posix compliant. This field username in the users table is also used for account validation. If you need something else, please create a new field in the user table and dont break the user validation funcationality
 
https://github.com/hopshadoop/hopsworks/commit/e3aad01af154c395a6d48e197caed36e2a489b10#diff-19ed1a8182ad11a585b1a420b51617e0R470

**Comment by gholamiali** [comment]
For example for this email: **aligh.workbox@gmail.com**
I got this username with 7 chars: **aligh_w**

The username should be at least "8 char"

**Comment by jimdowling** [comment]
What's your suggestion, Ali? Increase it to 8 characters? Does it break anything with 7 characters (apart from being non posix-compliant). If there's a collision, the function appends a  number, beginning at 000.

**Comment by gholamiali** [comment]
Correct, if it is less than 8 chars then account validation function gets confused. As long as it is equal to 8 chars it is fine. It does not even needs to be POSIX compliant.

Though having it as POSIX compliant would help in case of integrating it with an LDAP server or federated authentication in future...
