### ISSUE TITLE
Fix attaching a template to specific file

### ISSUE THREAD

**Issue by evsav** [hopshadoop/hopsworks#76]
There is no inode - template id association persisted in the corresponding table when the user picks a template for an uploaded file

**Comment by evsav** [comment]
Fixed. 

Although I'm not that sure about the many to many relationship between inodes and templates. A template is reasonable to be attached to many files, but can a file have multiple templates attached to it?

**Comment by jimdowling** [comment]
The most common use case is to reuse a template for multiple files. I think we can ignore multiple templates per inode for the moment, unless it's trivial to implement. The advantage of having multiple templates per file is that you can compose them and update them in a single place. For example, if a file concerns an individual, you may have an "Address" template. You would like to reuse that in lots of places. So, I guess the tables could be reused, but a template is a collection of tables. So the template doesn't need to be reused. Does that make sense? Unless the template is the unit of reuse, then you would need to design an address template, a personal-number template, etc. Then you could import them into a new template.
