### ISSUE TITLE
Redesign job running

### ISSUE THREAD

**Issue by stigviaene** [hopshadoop/hopsworks#77]
We'll provide:
* Ability to create a job. This defines the file you're running the job with (e.g. jar, .cf workflow,...) and the input parameters, run configurations like application master memory.
* Ability to schedule jobs. Choose whether you run a job now, at a specific time and whether you want to repeat it.
* A history of completed and ongoing executions, with their logs and, if possible, output files.

**Comment by jimdowling** [comment]
How's this going?

**Comment by stigviaene** [comment]
The split between jobs and executions has been implemented. The frontend needs some designing, but the functionality is there. Scheduling jobs has not been implemented yet.

**Comment by stigviaene** [comment]
Frontend has been redesigned. Scheduling remains to be done.

**Comment by stigviaene** [comment]
Scheduling works now. I updated the hopsworks.sql schema to include the glassfish timers table.

You need to set the EJB timer service to use the same JDBC resource as the hopsworks database. Otherwise we get an error (Local transaction already has 1 non-XA Resource: cannot add more resources). In my setup, I use jdbc/hopsworks, which points to the hopsworks database specifically. This does not interfere with the access to the hops database.

**Comment by stigviaene** [comment]
Remains to be done: cancelling a scheduled execution.

**Comment by jimdowling** [comment]
Have you pushed this yet? If not, can you update the schema in hopsworks-chef and push that as well when you merge this into develop?

**Comment by stigviaene** [comment]
Merged into develop and created pull request hopsworks-chef#3
